theme: jekyll-theme-midnight
title: Payload
author: Kromey
show_downloads: false
paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "Devlog"
